# _config.yml
title: Vikas Fugoki
description: Developer & Tech Enthusiast
baseurl: ""
url: "https://vikasfugoki.github.io"

# Author information
author:
  name: Vikas Fugoki
  email: your.email@example.com
  github: vikasfugoki123
  linkedin: your-linkedin-profile

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - resume.md
  - blog.md

# Collections for blog posts
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Vikas Fugoki"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# Social media and contact
social:
  github: vikasfugoki123
  email: your.email@example.com
  linkedin: your-linkedin-profile

# Google Analytics (optional - add your tracking ID)
# google_analytics: UA-XXXXXXXXX-X

# Disqus comments (optional)
# disqus:
#   shortname: your-disqus-shortname
