# _config.yml for Project Page Setup
# Repository: vikasfugoki123.github.io
# Site URL: https://vikasfugoki.github.io/vikasfugoki123.github.io
title: Vikas Fugoki
description: Developer & Tech Enthusiast

# IMPORTANT: For project pages, baseurl must match repository name
baseurl: "/vikasfugoki123.github.io"
url: "https://vikasfugoki.github.io"

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Author information
author:
  name: Vikas Fugoki
  email: your.email@example.com
  github: vikasfugoki

# Navigation
header_pages:
  - index.md
  - resume.md
  - blog.md

# Collections for blog posts
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Vikas Fugoki"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
